name: Promote/Rollback

on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
      branch:
        required: true
        type: string
      mode:
        required: false
        type: string
      requestor:
        required: true
        type: string
      operation:
        required: true
        type: string
      site_registration_id:
        required: true
        type: string

jobs:
  promotion_api:
    name: "Promotion/Rollback for ${{ inputs.branch }}"
    runs-on: self-hosted
    env: 
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    environment: ${{ inputs.branch }}
    steps:
      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client -y

      - name: Define reusable functions
        id: define-functions
        run: |
          # Function to set up database connection
          setup_db_connection() {
            export PGPASSWORD="${{ env.DB_PASSWORD }}"
            db_connection="psql -h ${{ env.DB_HOST }} -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }} -p ${{ env.DB_PORT }} --quiet"
          }

          # Function to get the latest seqno
          get_latest_seqno() {
            seqno=$($db_connection -t -c "SELECT seqno FROM schema.table_name ORDER BY seqno DESC LIMIT 1;" | xargs)
            echo $seqno
          }

          # Function to insert a new record and return the new seqno
          insert_new_record() {
            local site_action_cd="$1"
            local branch_action="$2"
            local new_seq_no=$($db_connection -t -c "INSERT INTO schema.table_name(seqno, rgs_id, site_action_cd, requestor, auto_promote, stage_env_cd, deploy_sts_cd, dt_deploy_started, created_by, created_date) VALUES (nextval('schema.MY_SEQNO'), ${{ inputs.site_registration_id }}, '$site_action_cd', '${{ inputs.requestor }}', 'N', '${branch_action^^}', 'REQUESTED', CURRENT_DATE, '${{ inputs.requestor }}', CURRENT_DATE) RETURNING seqno;" | xargs)
            echo $new_seq_no
          }

          # Function to update record in DB after promotion/rollback
          update_record() {
            local seqno="$1"
            local deploy_sts_cd="$2"
            local comment="$3"
            $db_connection -c "UPDATE schema.table_name SET deploy_sts_cd='$deploy_sts_cd', modified_by='${{ inputs.requestor }}', modified_date=CURRENT_DATE, comments='$comment', dt_deploy_completed=CURRENT_DATE WHERE seqno=$seqno;"
          }

      - name: Set up DB connection
        id: setup-db
        run: |
          source <(cat "${{ steps.define-functions.outputs.content }}")
          setup_db_connection
          echo "DB connection is set up."

      - name: Retrieve seqno and insert new record
        id: insert-seqno
        run: |
          source <(cat "${{ steps.define-functions.outputs.content }}")

          latest_seqno=$(get_latest_seqno)
          echo "Retrieved seqno: $latest_seqno"

          branch_action=${{ inputs.branch }}
          if [ "${{ inputs.branch }}" == "stage" ]; then
            site_action_cd="PROMOTE_STAGE"
          elif [ "${{ inputs.branch }}" == "prod" ]; then
            site_action_cd="PROMOTE_PRODUCTION"
          fi

          new_seq_no=$(insert_new_record "$site_action_cd" "$branch_action")
          echo "New seqno: $new_seq_no"
          echo "SEQNO=$new_seq_no" >> $GITHUB_ENV

      - name: Obtain Access Token
        run: |
          response=$(curl -s -X POST "https://abc.com/as/token.oauth2" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.OAUTH_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.OAUTH_CLIENT_SECRET }}")

          echo "OAuth response: $response"
          access_token=$(echo "$response" | jq -r '.access_token')
          echo "Access Token: $access_token"
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Determine Version Based on Operation
        run: |
          if [ "${{ inputs.operation }}" == "promote" ]; then
            version="new"
            comment="Promote new version"
          elif [ "${{ inputs.operation }}" == "rollback" ]; then
            status_response=$(curl --location -k --request GET "https://abc.com/api/status/${{ inputs.site }}/${{ inputs.branch }}/")
            echo "Status API response: $status_response"
            current_target=$(echo "$status_response" | jq -r '.[] | select(.name=="current") | .target')
            lower_valid_target=$(echo "$status_response" | jq -r '.[] | select(.status=="valid" and .name < "'$current_target'") | .name' | sort -r | head -n 1)
            if [ -n "$lower_valid_target" ]; then
              version=$lower_valid_target
            else
              echo "No valid previous target found for rollback"
              exit 1
            fi
            comment="Rollback version $version"
          else
            echo "Invalid operation: ${{ inputs.operation }}"
            exit 1
          fi

          echo "VERSION=$version" >> $GITHUB_ENV
          echo "COMMENT=$comment" >> $GITHUB_ENV

      - name: Promotion/Rollback
        run: |
          response=$(curl --location -k --request POST "https://abc.com/api/job/start" \
            -d "site=${{ inputs.site }}" \
            -d "branch=${{ inputs.branch }}" \
            -d "requestor=${{ inputs.requestor }}" \
            -d "version=${{ env.VERSION }}" \
            -d "operation=${{ inputs.operation }}" \
            -d "mode=${{ inputs.mode }}" \
            -d "access_token=${{ env.ACCESS_TOKEN }}" )
          echo "API response: $response"

          api_status=$(echo "$response" | jq -r '.status')
          if [ "$api_status" == "success" ]; then
            api_version=$(echo "$response" | jq -r '.message' | grep -oP '\d+' | sed -n 2p)
            echo "Version: $api_version"
            echo "API_VERSION=$api_version" >> $GITHUB_ENV
            echo "API_STATUS=$api_status" >> $GITHUB_ENV
          else
            echo "API failed with status $api_status"
            exit 1
          fi

      - name: Update Record in Database
        run: |
          source <(cat "${{ steps.define-functions.outputs.content }}")

          if [ "$API_STATUS" == "success" ]; then
            deploy_sts_cd="SUCCESS"
          else
            deploy_sts_cd="FAILURE"
          fi
          update_record "${{ env.SEQNO }}" "$deploy_sts_cd" "${{ env.COMMENT }}"

      - name: Waiting for site to stabilize
        run: | 
          echo "Waiting for site to stabilize..."
          sleep 5m
