# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
     uses: ./.github/workflows/deploy.yml
  health-check:
    uses: ./.github/workflows/health.yml
    with: 
      DEPLOYMENT_TYPE: 'dev'
    secrets: inherit

  health-check-prod:
    uses: ./.github/workflows/health.yml
    with: 
      DEPLOYMENT_TYPE: 'prod'
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{github.repository}}/environments/${{inputs.DEPLOYMENT_TYPE}}/variables/URL
        

     
