name: CD

# Controls when the workflow will run
on:
  workflow_call:
jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy app
        run: echo "develop"
    
  health-check-dev:
    needs: deploy
    uses: ./.github/workflows/health.yml
    with: 
      DEPLOYMENT_TYPE: 'dev'
    secrets: inherit

  deploytoprod:
   if: github.ref === 'refs/heads/main'
   uses: ./.github/workflows/deploy.yml
   with: 
    DEPLOYMENT_TYPE: 'dev'
  
  health-check-prod:
    needs: deploytoprod
    uses: ./.github/workflows/health.yml
    with: 
      DEPLOYMENT_TYPE: 'dev'
    secrets: inherit

  
