name: health

on:
  workflow_call:
    inputs:
      DEPLOYMENT_TYPE:
        required: true
        type: string
      
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Test variables
        run: |
            echo "${{inputs.DEPLOYMENT_TYPE}}"
